<div class="showback">
    <h4><i class="fa fa-angle-right">Controlli l'edificio: <?php echo $this->staffedif ?></i></h4>
    <?php if('false'==$this->flag) :?>
    <?php echo 'Nessun avviso trovato' ?>
    <?php endif ?>
    <?php if('true'==$this->flag) :?>
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th  width="10%">Avvisi</th>
                    <th  width="10%">Piano</th>
                    <th  width="10%">N° segnalaziani</th>
                </tr>
            </thead>
        <tbody>
        <?php foreach ($this->piano as $pk => $p) :?>
            <?php foreach ($this->tipAvv as $tak => $ta) :?>
                <?php if($pk==$tak) :?>
                    
                     <tr>
                         <td width="20%"> <?php echo $ta['tipoAvviso'] ?> </td>
                         <td width="20%"> <?php echo $p['piano'] ?> </td>
                         <td width="20%"> <?php echo '$cou' ?> </td>
                         <td width="10%"> <a href="<?= $this->url(array(
                                                        'controller' => 'staff',
                                                        'action'     => 'evapiano',),
                                                        'default',true );?>/?avviso=<?php echo $ta['tipoAvviso'] ?>&aula=<?php echo $p['piano'] ?>">
                         <button title="avvia evaquazione" class="btn btn-warning btn-xs">
                         <i class="fa fa-warning "></i></button> </a></td>
                    </tr>
                        
                <?php endif ?>
            <?php endforeach ?>
         <?php endforeach ?>
     
        </tbody>
        </table>
    </div> 
    <?php endif ?>
</div>