<div class="showback">
    <h4><i class="fa fa-angle-right">Controlli l'edificio: <?php echo $this->staffedif ?></i></h4>
    Segnalazioni totali: <?php echo $this->tcou ?>
    <?php if('false'==$this->flag) :?>
    <?php echo 'Nessuna area trovata' ?>
    <?php endif ?>
    <?php if('true'==$this->flag) :?>
    <div>
        <table class="table">
    <thead>
        <tr>
           <th  width="10%">Tipo avviso</th>
           <th  width="10%">Piano</th>
           <th  width="10%">N° segnalaziani</th>
        </tr>
    </thead>
    <tbody>
    
            
            <tr>
                <td width="20%"> <?php echo '$t' ?> </td>
                <td width="20%"> <?php echo '$p' ?> </td>
                <td width="20%"> <?php echo '$c' ?> </td>
                <td width="10%"> <a href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'evapiano',),
                                                    'default',true );?>/?piano=<?php echo $p ?>&tipo=<?php echo $t['tipoAvviso'] ?>">
                        <button class="btn btn-warning btn-xs">
                        <i title="avvia evaquazione" class="fa fa-warning "></i></button> </a></td>
             </tr>
            
        <?php endif ?>
        </tbody>
       </table>
     </div> 
</div>
