<h2>EVAQUAZIONE</h2>
<div class="showback">
    <h4><i class="fa fa-angle-right"></i><?php echo $this->comp ?></h4>
    <?=$this->evaForm; ?>
            <table>Inserite dall'utente
        	<tr>
        		<td>Edificio</td>
        		<td>Aula</td>	
        		<td>Cataclisma</td>		
        	</tr>
	        <!-- <?php foreach ($this->comp as $s) :?> -->
	        <tr>
	        	<td>ok</td>
	        	<td>si</td>
	        </tr>
	        <?php endforeach ?>
        </table>
</div>
