
<?php if (($this->per) == NULL): ?>
<div class="showback">    	
    <h2>EVACUAZIONE</h2>	<h3><i class="fa fa-angle-right">Edificio: <?php echo $this->edificio ?></i></h3>
    	<br>
        <?=$this->evaForm; ?>		
     </div> 
</div>
<?php else: ?>
<div class="showback">    	
    <h2>EVACUAZIONE</h2>	<h3><i class="fa fa-angle-right">Edificio: <?php echo $this->edificio ?></i></h3>
    	<br>
        <a href="<?= $this->url(array('controller' => 'staff',
                                      'action'     => 'evaannull', ), 
                                      'default',true );?>"><button class="btn btn-round btn-default">
                INTERROMPI EVACUAZIONE</button>	</a>	
     </div> 
</div>
<?php endif;?>