<h2>EVAQUAZIONE</h2>
<hr>
<div class="showback">
    <h4><i class="fa fa-angle-right"><?php echo $this->comp ?></i></h4>
    <div>
        <table>Inserite dall'utente
        	<tr><td>Edificio</td><td>Aula</td><td>Cataclisma</td></tr>
        		
        		
        			
        	
	        <!-- <?php foreach ($this->comp as $s) :?> -->
	        
	        
	        <!--<?php endforeach ?>-->
        </table> <?=$this->evaForm; ?>
     </div> 
</div>
