

<h2>GESTIONE PERCORSI</h2>
<hr>
<div class="showback"> 
	
	<h4>Edificio "<?php echo $this->comp ?>"</h4> 
    <h4><i class="fa fa-angle-right">Seleziona le vie di fuga relative ad ogni Piano e ad ogni zona di evacuazione</i></h4>
   
    <?=$this->gForm; ?> 

    <table class="table">
   	 <thead>
        <tr>
           <th  width="15%">Mappa</th>
           <th  width="15%">Zona</th>  	  
        </tr>
    </thead>   
    
     <tbody id="tabEvac">
     	 
    </tbody>
	</table>
	<button id="btnc" class="btn btn-round btn-default" onClick="VerificaIns()" "display:none">CONFERMA SELEZIONE</button>
    
</div>
