<h2>HOME</h2>
<div class="showback">
    <h4><i class="fa fa-angle-right"></i>Notifiche segnalazioni <b><?php echo $this->comp ?></b></h4>		
   	<p class="left">
   		
   		<?php foreach ($this->image as $i) :?>
        <div class="Domanda">
            <?php echo '<h3>mappa: ' . $i->image . '</h3>' ?>
        </div>
            <?php echo'<h4">mappa: ' . $i->image . '</h4>' ?>
        <?php endforeach ?>
    		<?php  echo $this->image; ?>	
    
    </p>
    	
    
    <div>
    
    	
    		
    </div> <?=$this->hForm; ?>
</div>
