<h2>SEGNALAZIONI</h2>
<div class="content-panel">
    <?php echo '<h2><i class="fa fa-angle-right">Segnalazioni per area:</i> ' .$this->authInfo('posizioneStaff').'</h2>' ?>
    <hr>

	<table class="table">
   	 <thead>
        <tr>
           <th  width="15%">Edificio</th>
           <th  width="15%">Piano</th>
           <th  width="15%">Aula</th>
           <th  width="40%">Tipo Avviso</th>
           <th  width="15%">Data</th>   	  
        </tr>
    </thead>   
	       <?php foreach ($this->avvStaff as $af) :?>
		   <?php foreach ($this->elAvvStaff as $eaf) :?>
		   <?php if($af->idElencoAvviso==$eaf->idElencoAvviso) :?>
		   <?php foreach ($this->posStaff as $pf) :?>
		   <?php if($af->idPosizione==$pf->idPosizione) :?>
		   <?php if($pf->edificio==$this->authInfo('posizioneStaff')) :?>	
		 <tbody> 
            <tr>    
                <td width="15%"> <?php echo $pf->edificio ?> </td>
                <td width="15%"> <?php echo $pf->piano ?> </td>
                <td width="15%"> <?php echo $pf->aula ?> </td>
                <td width="30%"> <?php echo $eaf->tipoAvviso ?> </td>
                <td width="15%"> <?php echo $af->data ?> </td>
                <td width="10%"> 
                <a href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'aggiungisegnalazione',),
                                                    'default',true );?>/?segnalazione=<?php echo $af->idAvviso ?>">
                    <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button> 
                </a></td>                  
                <td width="10%"> <a href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'deletesegnalazione',),
                                                    'default',true );?>/?segnalazione=<?php echo $af->idAvviso ?>">
                                   <button class="btn btn-danger btn-xs">
                                   <i class="fa fa-trash-o "></i></button> 
                </a></td>
             </tr>
 		   <?php endif ?>
		   <?php endif ?>  
		   <?php endforeach ?>
		   <?php endif ?>
		   <?php endforeach ?>
		   <?php endforeach ?>
    	</tbody>
	</table>
</div>
		 	
		 	
		 	
		 	
		 

    
    
    
    