	<div class="showback"> 
		<h1><i class="fa fa-angle-right"><b>Benvenuto nel nostro sito</b></h1></i>	
		<br><br>
        	<p class="fa-fhome "> L'obiettivo che si prefigge la nostra applicazione web è la gestione delle emergenze (terremoti, incendi, crolli di 
				porzioni di edifici ...) fornendo indicazioni sui percorsi sicuri di fuga da locali chiusi per gli occupanti 
				degli  stessi. Il nostro servizio è in grado di fornire le planimetrie con i relativi percorsi di fuga 
				personalizzati in base alle diverse tipologie di emergenze. </p>
        	<p class="fa-fhome "> Il sistema acquisisce la posizione di ogni utente registrato all’interno dell’edificio in cui 
                si trova ed eventuali indicazioni di situazioni di pericolo segnalate dallo stesso. Su richiesta, fornisce una mappa 
                con l’indicazione della via di fuga più sicura per l’evacuazione, in relazione alla posizione del richiedente e alle 
                situazioni di pericolo in essere nell’edificio. </p>
                <br><br>
            <a href="<?= $this->url(array(
                          'controller' => 'access',
                          'action'     => 'login', ), 
                          'default',true );?>">  
            <h3><i class="fa fa-angle-right"><b>Effettua il login o registrati per usufruire dei nostri servizi</i></b></h3></a>         
	</div>