<div class="showback">
    <h2><i class="fa fa-angle-right"></i>CHI SIAMO</h2>
    <div class="static">
    	<h3> La nostra società</h3>    
    	    <p>  Siamo 4 ragazzi da tutta italia con una comune passione, programmare. Il nostro gruppo crea servizi web su richiesta e 
    	    	 senza richiedere compensi, al massimo donazioni</p>
    	 
    	<h3> Obiettivo del servizio </h3>
        	<p> L'obiettivo che si prefigge la nostra applicazione web è la gestione delle emergenze (terremoti, incendi, crolli di 
				porzioni di edifici ...) fornendo indicazioni sui percorsi sicuri di fuga da locali chiusi per gli occupanti 
				degli  stessi. Il nostro servizio è in grado di fornire le planimetrie con i relativi percorsi di fuga 
				personalizzati in base alle diverse tipologie di emergenze. </p>
        	<p> Il sistema acquisisce la posizione di ogni utente registrato all’interno dell’edificio in cui 
                si trova ed eventuali indicazioni di situazioni di pericolo segnalate dallo stesso. Su richiesta, fornisce una mappa 
                con l’indicazione della via di fuga più sicura per l’evacuazione, in relazione alla posizione del richiedente e alle 
                situazioni di pericolo in essere nell’edificio. </p>
                <br>
     </div>
   
        
	