<div class="showback">
    <h2><i class="fa fa-angle-right"></i>CHI SIAMO</h2>
    <div class="static">
    	<h3> La nostra società</h3>    
    	    <p>  Siamo 4 ragazzi da tutta italia con una comune passione, programmare. Il nostro gruppo, dal 2016, crea servizi web su richiesta e 
    	    	 senza richiedere compensi, al massimo donazioni.</p>
    	 
    	<p>Il sito da noi creato è frutto di tante problematiche e difficoltà nella gestione delle emergenze che sono venute fuori durante gli anni.
    		Il nostro gruppo si è fatto carico di trovare una soluzione semplice e facilmente implementabile anche in caso un utente si facesse prendere dal panico</p>
     </div>
   
        
	