<script type="text/javascript">

            var http = getXMLHTTPRequest();
            
            function getXMLHTTPRequest(){
                try {
                    req = new XMLHttpRequest();
                } 
                catch (err1) {
                    try {
                        req = new ActiveXObject("Msxml2.XMLHTTP");
                    } 
                    catch (err2) {
                        try {
                            req = new ActiveXObject("Microsoft.XMLHTTP");
                        } 
                        catch (err3) {
                            req = false;
                        }
                    }
                }
                return req;
            }
            
            function getPiano(piano){
                if ( == "-- Seleziona --") {
                    document.forms['miaform'].piano.options.length = 0;
                    return
                }
                var modurl = 'plan.php?ed=' + edificio;
                
                // Inizializza XMLHttpRequest - il terzo parametro definisce la richiesta asincrona (true) o sincrona (false)
                http.open("GET", modurl, true);
                
                // Definisce la funzione di callback
                http.onreadystatechange = useHttpResponse;
                
                // Invia la richiesta al server 
                http.send();
            }
            
            function useHttpResponse(){
                /*
                 // Valori di readyState che rappresentano lo stato dell'oggetto XMLHttpObject
                 
                 0: Uninitalized. Oggetto non inizializzato;
                 1: Open. Attivato con successo im metodo open()
                 2: Sent. Richiesta inoltrata al server
                 3: Receiving. Ricevuto l'header della risposta (ma non il body)
                 4: Loaded. La risposta  stata ricevuta
                 */
                if (http.readyState == 4) {
                    if (http.status == 200) {
                        // Risposta OK
                        var pianList = http.responseXML.getElementsByTagName("piano");
                        document.forms['miaform'].piano.options.length = 0;
                        for (i = 0; i < pianList.length; i++) {
                            document.forms['miaform'].piano.options[i] = new Option(pianList[i].childNodes[0].nodeValue, i);
                        }
                    }
                }
            }                    

            window.onload = function() {
                document.getElementById('selReg').onchange = function(){
                    getPiano(this.options[this.selectedIndex].text);
                }
            };

        </script>
    </head>

    

