<aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
                  <h5 class="centered">Accedi o registrati per utilizzare i servizi</h5>
                  
                  <li class="mt">
                      <a class="active" href="<?= $this->url(array(
                                                    'controller' => 'public',
                                                    'action'     => 'index', ), 
                                                    'default',true );?>">
                          <i class="fa fa-dashboard"></i>
                          <span>HOME</span>
                      </a>
                  </li>
                  
                  <li class="mt">
                      <a class="sub-menu" href="<?= $this->url(array(
                                                    'controller' => 'access',
                                                    'action'     => 'registrazione', ), 
                                                    'default',true );?>">
                          <i class="fa fa-dashboard"></i>
                          <span>REGISTRATI</span>
                      </a>
                  </li>
                 
                   <li class="mt">
                       <a href="javascript:;" >
                          <i class="fa fa-dashboard"></i>  
                          <span>INFORMAZIONI</span>  
                       </a>
                      	  <ul class="sub">
                         	 <li><a  class="sub-menu" href="<?= $this->url(array(
                                                    'controller' => 'public',
                                                    'action'     => 'informazioni generali', ), 
                                                    'default',true );?>">Modifica</a></li>
                          	<li><a  class="sub-menu" href="<?= $this->url(array(
                                                    'controller' => 'public',
                                                    'action'     => 'index', ), 
                                                    'default',true );?>">Visualizza</a></li>
                         	<li><a  class="sub-menu" href="<?= $this->url(array(
                                                    'controller' => 'public',
                                                    'action'     => 'FAQ', ), 
                                                    'default',true );?>">Credenziali</a></li>
                       </ul> 
                   </li>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      