 <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
                  <?php
                  $base64 = base64_encode($this->authInfo('imgprofilo'));
                  $image = '<img src="data:image/gif;base64,' . $base64 . '" class="img-circle" width="60" />';
                  ?>
                  <p class="centered"><?php echo $image ?></a></p>
                  <h5 class="centered"><?php echo $this->authInfo('nome') . ' ' . $this->authInfo('cognome') ?></h5>
                 
                  <li class="mt">
                      <a class="active" href="<?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'index', ), 
                                                    'default',true );?>">
                          <i class="fa fa-dashboard"></i>
                          <span>Home</span>
                      </a>
                  </li>

                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-desktop"></i>
                          <span>Profilo</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="Ingegneria_Segn.html">Modifica</a></li>
                          <li><a  href="Medicina_Segn.html">Visualizza</a></li>
                          <li><a  href="Economia_Segn.html">Credenziali</a></li>
                      </ul>
                  </li>
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      