 <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
                  <p class="centered"><a href="profile.html"><img src="" class="img-circle" width="60"></a></p>
                  <h5 class="centered">Mingo Filippo</h5>
                 
                  <li class="mt">
                      <a class="active" href="index.html">
                          <i class="fa fa-dashboard"></i>
                          <span>Home</span>
                      </a>
                  </li>

                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-desktop"></i>
                          <span>Segnalazioni</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="Ingegneria_Segn.html">Ingegneria</a></li>
                          <li><a  href="Medicina_Segn.html">Medicina</a></li>
                          <li><a  href="Economia_Segn.html">Economia</a></li>
                      </ul>
                  </li>
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      