 <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
                   <?php
                  $base64 = base64_encode($this->authInfo('imgprofilo'));
                  $image = '<img src="data:image/gif;base64,' . $base64 . '" class="img-circle" width="60" />';
                  ?>
                  <p class="centered"><?php echo $image ?></a></p>
                  <h5 class="centered"><?php echo $this->authInfo('nome') . ' ' . $this->authInfo('cognome') ?></h5>
                 
                  <li class="mt">
                  		 <a  href="<?= $this->url(array(
                                            'controller' => 'staff',
                                            'action'     => 'home',), 
                                            'default',true );?>">
                 		 	<i class="fa fa-dashboard"></i>	 
                  		 	<span>Home</span>
                  	 	 </a>  
                  </li>

				 <li class="mt">
				 	  <a  href="javascript:;" >
                 		 <i class="fa fa-dashboard"></i>	 
                   <span>Profilo</span></a>         	
                         <ul class="sub">
                          <li><a  href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'profilo', ), 
                                                    'default',true );?>">Visualizza profilo</a></li>
                          <li><a  href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'modprofilo', ), 
                                                    'default',true );?>">Modifica profilo</a></li>
                          <li><a  href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'modcredenziali', ), 
                                                    'default',true );?>">Modifica credenziali</a></li>
                    	</ul>
                  </li>
                  
                  <li class="mt">
				 	  <a  href="javascript:;" >
                 		 <i class="fa fa-dashboard"></i>	 
                   <span>Gestione Evaquazione</span></a>
                         <ul class="sub">
                          <li><a  href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'gestione', ), 
                                                    'default',true );?>">Percorsi</a></li>
                          <li><a  href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'modprofilo', ), 
                                                    'default',true );?>">Segnalazioni</a></li>
                          <li><a  href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'modcredenziali', ), 
                                                    'default',true );?>">Modifica credenziali</a></li>
                    	</ul>
                  </li>
                  
                  <li class="mt">
                      <a  href="javascript:;" >
                          <i class="fa fa-desktop"></i>
                          <span>Evaquazione Area</span>
                      </a>
                      <ul class="sub">
                      	  <li><a href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'gestione',), 
                                                    'default',true );?>">
                         	  <span>Ingegneria</span></a>
                          </li>
                          
                          <li><a href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'index',), 
                                                    'default',true );?>">
                         	  <span>Medicina</span></a>
                          </li>
                          
                          <li><a href="<?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'profilo',), 
                                                    'default',true );?>">
                         	  <span>Economia</span></a>
                          </li>
                          
                      </ul>
                  </li>
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      