 <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
                  <?php
                  $base64 = base64_encode($this->authInfo('imgprofilo'));
                  $image = '<img src="data:image/gif;base64,' . $base64 . '" class="img-circle" width="60" />';
                  ?>
                  <p class="centered"><?php echo $image ?></a></p>
                  <h5 class="centered"><?php echo $this->authInfo('nome') . ' ' . $this->authInfo('cognome') ?></h5>
                  <li class="mt">
                     <a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'index',), 
                                                    'default',true );?>"> 
                          <i class="fa fa-desktop"></i>
                          <span>Home</span>
                      </a>
                  </li>

                  <li class="sub-menu">
                      <a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'user',), 
                                                    'default',true );?>"> 
                          <i class="fa fa-user"></i>
                          <span>Gestione utenti</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                       <a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'planimetria',), 
                                                    'default',true );?>"> 
                          <i class="fa fa-map-marker"></i>
                          <span>Gestione planimetrie</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'mappaevaquazione',), 
                                                    'default',true );?>"> 
                          <i class="fa fa-flash"></i>
                          <span>Gestione evacuazione</span>
                      </a>
                  </li>
                  <li  class="sub-menu"><a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'faq',), 
                                                    'default',true );?>">                        
                      <i class="fa fa-question-circle"></i>
                      <span>Gestione FAQ</span>
                      </a>
                  </li>
              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      