<div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
              </div>
            <!--logo start-->
            <a href="index.html" class="logo"><b>UNIVPM EMERGENCY</b></a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
            </div>
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" href="    <?= $this->url(array(
                                                    'controller' => 'access',
                                                    'action'     => 'login', ), 
                                                    'default',true );?>"
                                                 ">Login</a></li>
                </ul>
            </div>