<?php echo $this->doctype(); ?>
<html>
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->render('js_admin.phtml');?>
</head>
<body>
<section id="container" >
 
      <!--header start-->
      <header class="header black-bg">
              <?= $this->render('_topadmin.phtml') ?>
      </header>
      <!--header end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <?= $this->render('_sidebarAdmin.phtml') ?>
      <!--sidebar end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">

              <div class="row">
                  <div class="col-lg-12 main-chart">         
                    
                    <?php echo $this->layout()->content; ?>
                    
                  </div><!-- /col-lg-9 END SECTION MIDDLE -->
              </div> 
          </section>
      </section>
      <!--footer start-->
      <?= $this->render('footer.phtml') ?>
      <!--footer end-->
 </section>
  <?= $this->render('js.phtml') ?> 
</body>
</html>