<script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"></script>

<script>
    
        
        
    function AggiungiAula()
    { 
      var id = $("#id").val();  
            
      new Ajax.Request(
      "<?=$this->url(array('controller' => 'admin','action' => 'aggiungiaula'))?>",
                {
                    method:'POST',
                    parameters: {id: id},
                    onSuccess: function (newElement) {
                            console.log(newElement);
                            
                            var a = document.getElementById('tabellaAddPlan');
                            var b = document.getElementsByTagName('tbody');
                            var countTr = document.getElementsByTagName('tr').length;
                            b[0].id = 'bodyTab';
                            
                            var tr = document.createElement('tr');
                            tr.innerHTML = newElement.responseText;
                            document.getElementById('bodyTab').appendChild(tr);
                    
                            // Increment and store id
                            $("#id").val(++id);
                            }
                        
            });
        }
  
    
</script>