<script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"></script>
<script>

    function AggiungiAula()
    {
      var id = $("#aula").val();            
      new Ajax.Request(
      "<?=$this->url(array('controller' => 'admin','action' => 'aggiungiaula'))?>",
                {
                    method:'POST',
                    data: 'id='+id,
                    onSuccess: function FillMapP(mappaRsp)
                               {
                                    var mappaEmap = eval('(' + mappaRsp.responseText + ')');
                                    var mappa = document.getElementById('mappaPosizione');
                                    mappa.src = mappaEmap.mappa;
                                    var map = document.getElementById('mapPosizione');
                                    map.innerHTML = mappaEmap.map;  
                                    mappa.setAttribute("usemap", "#mapPosizione");
                                    
                                    var area = map.getElementsByTagName("area"); 
                                    for (var i = 0; i < area.length; i++) { 
                                        var a = i+1;
                                        var url = "<?= $this->url(array('module'=>'default','controller' => 'user','action' => 'aulaevacuazione'))?>";
                        
                                        var status = area[i].setAttribute("href", url+"/aue/"+a);   
                                    }                                   
                               }
            });
        }
    }
    
</script>