<div class="col-lg-3 ds">
                      <!--COMPLETED ACTIONS DONUTS CHART-->
                        <h3>NOTIFICHE</h3>
                       
                                       
                     
                      <?php foreach ($this->dataNotifica as $key=>$data) :?>
                      
                      <!-- notifica -->
                      <div class="desc">
                                <div class="thumb">
                                    <span class="badge bg-theme"><i class="fa fa-clock-o"></i></span>
                                </div>
                            <div class="details">
                            <?php foreach ($this->doveNotifica as $dove) :?>   
                            <?php if($data->idPosizione==$dove->idPosizione) :?>
                            <?php foreach ($this->tipoNotifica as $tipo) :?>
                            <?php if($data->idElencoAvviso==$tipo->idElencoAvviso) :?>
                            <?php echo '<p><muted> '. $data->data .' </muted><br/>'. $tipo->tipoAvviso .' </muted><br/>'. $dove->edificio .','. $dove->piano .','. $dove->aula .'<br/></p>' ?>
                            <?php endif ?>
                            <?php endforeach ?>
                            <?php endif ?>
                            <?php endforeach ?>
                            

                            </div>
                      </div>
                       
                        <?php endforeach ?>
</div>