<?php echo $this->doctype() ?>
<html>
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->render('js_staff.phtml');?>
    <script>
    function FillPiani()
    {
    	//Metodo per prelevare l'elemento selezionato nel select
    	var e = document.getElementById('edificio');
		var edificio = e.options[e.selectedIndex].text;
		//Metodo per rimuovere tutti gli elementi e reinserire solo "-- Seleziona Piano --"
		$('#piano').find('option').remove().end().append('<option value="pian">-- Seleziona Piano --</option>').val('pian');
        new Ajax.Request(
        "<?=$this->url(array('controller' => 'user','action' => 'piano'))?>",
            {
                method:'get',
                parameters: {edif: edificio},
                onSuccess: function FillSelPiani(rsp)
						   {
						   		var piani = eval('(' + rsp.responseText + ')');
						   		var dim = piani.length;
								//Creazione dinamica del selettore
     							var select = document.getElementById('piano');
     							for (var i = 0; i<dim; i++){
								    var elemento = document.createElement('option');
								    elemento.innerHTML = piani[i].piano;
								    select.appendChild(elemento);
								}
						   }
        });
	}
    </script>
</head>
<body>
<section id="container" >
      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT 
      *********************************************************************************************************************************************************** -->
      <!--header start-->
      <header class="header black-bg">
              <?= $this->render('_topstaff.phtml') ?>
      </header>
      <!--header end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <?= $this->render('_sidebarStaff.phtml') ?>
      <!--sidebar end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">

              <div class="row">
                  <div class="col-lg-9 main-chart">         
                    
                    <?php echo $this->layout()->content; ?>
                    
                  </div><!-- /col-lg-9 END SECTION MIDDLE -->
              </div> 
          </section>
      </section>
      <!--footer start-->
      <?= $this->render('footer.phtml') ?>
      <!--footer end-->
 </section>
  <?= $this->render('js.phtml') ?> 
</body>
</html>