

<?php if (($this->idPos) == NULL): ?>
<h2>INDICA LA TUA POSIZIONE</h2>
<div class="showback">
    <h3><i class="fa fa-angle-right"></i>DOVE SEI?</h3>
    <?=$this->pForm; ?>
</div>
<div class="showback">
    <h3><i class="fa fa-angle-right"></i>MAPPA</h3>
    Indica la tua posizione sulla mappa:
    <br>
    <img id="mappaPosizione" />
    <map id="mapPosizione" name="mapPosizione"></map>
</div>
<?php else: ?>
 <div class="showback">
 	<h3><i class="fa fa-angle-right"></i>POSIZIONE ATTUALE</h3>
 	<div style="float:left; ">	 	
		    <p>Edificio: <?=$this->data['edificio']; ?><br></p>
		    <p>Piano: <?=$this->data['piano']; ?><br></p>
		    <p>Aula: <?=$this->data['aula']; ?><br></p><br>
		    <h3><i class="fa fa-angle-right"></i>MODIFICA POSIZIONE</h3>
    		<a href="<?= $this->url(array(
                          'controller' => 'user',
                          'action'     => 'modificaposizione',), 
                          'default',true );?>"> 
    		<p>Modifica posizione attuale<br></p></a>
	</div>
	<div style="float:left display:inline" align="center">  
	    	<img  src = <?=$this->planimetriaCorretta; ?> width = "40%" height = "40%"/>
	</div>
	<div style="clear:both;"></div>	   
</div> 

<div class="showback">
    <h3><i class="fa fa-angle-right"></i>INVIA SEGNALAZIONE</h3>
    <?=$this->seForm; ?>
    <br>
    Indica la posizione della segnalazione:
    <img id="mappaSegnalazione" />
    <map id="mapSegnalazione" name="mapSegnalazione"></map>
</div>
 


<?php endif;?>