<div class="showback">
                        <h4><i class="fa fa-angle-right"></i>IL TUO PROFILO</h4>
                        
                        <div>
                          <h5>NOME:</h5><h4><?php echo $this->authInfo('nome')?></h4>
                        </div>
                        <div>
                          <h5>COGNOME:</h5><h4><?php echo $this->authInfo('cognome')?></h4>
                        </div>
                        <div>
                          <h5>ETA':</h5><h4><?php echo $this->authInfo('eta')?></h4>
                        </div>
                        <div>
                          <h5>TELEFONO:</h5><h4><?php echo $this->authInfo('telefono')?></h4>
                        </div>
                        <div>
                          <h5>INDIRIZZO:</h5><h4><?php echo $this->authInfo('indirizzo')?></h4>
                        </div>
                        <div>
                          <h5>MAIL:</h5><h4><?php echo $this->authInfo('email')?></h4>
                        </div>
                        <div>
                          <h5>SESSO:</h5><h4><?php echo $this->authInfo('genere')?></h4>
                        </div>
</div>