<div class="showback">
                        <h4><i class="fa fa-angle-right"></i>IL TUO PROFILO</h4>
             <table class="table"> 
                 <tbody>
                        <tr>
                            <td>NOME:</td>
                            <td><?php echo $this->authInfo('nome')?></td>
                        </tr>
                        
                        
                        <tr>
                          <td>COGNOME:</td>
                          <td><?php echo $this->authInfo('cognome')?></td>
                        </tr>
                        
                        <tr>
                          <td>ETA':</td>
                          <td><?php echo $this->authInfo('eta')?></td>
                        </tr>
                        
                        <tr>
                          <td>TELEFONO:</td>
                          <td><?php echo $this->authInfo('telefono')?></td>
                        </tr>
                        
                        <tr>
                          <td>INDIRIZZO:</td>
                          <td><?php echo $this->authInfo('indirizzo')?></td>
                        </tr>
                        
                        <tr>
                          <td>MAIL:</td>
                            <td><?php echo $this->authInfo('email')?></td>
                        </tr>
                        
                        <tr>
                          <td>SESSO:</td>
                          <td><?php echo $this->authInfo('genere')?></td>
                        </tr>
                        
                        
                </tbody>
       </table> 
</div>