<div class="content-panel">
<table class="table">
    <thead>
        <tr>
           <th  width="30%">Domanda</th>
           <th  width="70%">Risposta</th>
           <th  width="5%">
               <a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'aggiungifaq',),
                                                    'default',true );?>">
                        <button class="btn btn-success btn-xs"><i class="fa fa-plus"></i></button></a>

           </th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach ($this->faq as $f) :?>  
            <tr>
                <td width="20%"><?php echo $f->domanda ?> </td>
                <td width="60%"> <?php echo $f->risposta ?> </td>
                <td width="10%"> <a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'modfaq',),
                                                    'default',true );?>/?idfaq=<?php echo $f->idFaq ?>">
                       <button class="btn btn-primary btn-xs">
                       <i class="fa fa-pencil"></i></button> </a></td>
                <td width="10%"> <a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'deletefaq',),
                                                    'default',true );?>/?idfaq=<?php echo $f->idFaq ?>">
                        <button class="btn btn-danger btn-xs">
                        <i class="fa fa-trash-o "></i></button> </a></td>
                </tr>
        <?php endforeach ?>
    </tbody>
</table>
</div>