<div class="showback"> 
    <h1><i class="fa fa-angle-right">Benvenuto Admin!</i></h1>
    <hr>
    Area ad accesso esclusivo dell’amministratore del sito che consente:
    <ul>
       <li>la gestione (creazione/modifica/cancellazione) degli immobili gestiti, delle relative planimetrie,
           delle zone e dei percorsi di fuga;</li>
       <li>la gestione di tutti gli utenti del sito (staff incluso)</li>
       <li> l’aggiornamento delle FAQ</li>
    </ul>
</div>
