<div class="content-panel">
    
    <?php
        // Creo il paginator
        $paginator = Zend_Paginator::factory($this->planimetria);
        // Setto il numero di elementi per pagina (in questo caso 3)
        $paginator->setItemCountPerPage(3);
        // Controlla se vi è una GET se true prende la variabile page e la passa al paginator
        if($_GET){
        $page = $_GET['page'];
        $paginator->setCurrentPageNumber($page);
        }
     ?>
     
<table class="table">
    <thead>
        <tr>
           <th  width="40%">Mappa</th>
           <th  width="30%">Edificio</th>
           <th  width="30%">Piano</th>
           <th  width="5%">
               <a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'aggiungiplanimetria',),
                                                    'default',true );?>">
                        <button class="btn btn-success btn-xs"><i class="fa fa-plus"></i></button></a>

           </th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach ($paginator as $fk=>$f) :?>  
             <?php
                  $base64 = base64_encode($f->mappa);
                  $image = '<img src="data:image/jpg;base64,' . $base64 . '" width="250" />';
                  ?>
            <tr>
                <td width="30%">   <?= $image  ?> </td>
                <td width="30%">   <?= $this->posizione[$fk]['edificio']  ?> </td>
                <td width="30%">   <?= $this->posizione[$fk]['piano']  ?> </td>
                <td width="10%"> <a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'modificaplanimetria',),
                                                    'default',true );?>/?idplan=<?php echo $f->idPlanimetria ?>">
                       <button class="btn btn-primary btn-xs">
                       <i class="fa fa-pencil"></i></button> </a></td>
                <td width="10%"> <a href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'deleteplanimetria',),
                                                    'default',true );?>/?idplan=<?php echo $f->idPlanimetria ?>">
                        <button class="btn btn-danger btn-xs">
                        <i class="fa fa-trash-o "></i></button> </a></td>
                </tr>
        <?php endforeach ?>
    </tbody>
</table>
    <?php echo $this->paginationControl($paginator,
                                    'Sliding',
                                    'admin/_paginatorPlan.phtml'); ?>
</div>