<div class="content-panel">
<table class="table">
    <thead>
        <tr>
           <th  width="15%">Nome</th>
           <th  width="15%">Cognome</th>
           <th  width="15%">Username</th>
           <th  width="40%">email</th>
           <th  width="15%">livello</th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach ($this->user as $f) :?>  
            <tr>
                <td width="15%"><?php echo $f->nome ?> </td>
                <td width="15%"> <?php echo $f->cognome ?> </td>
                <td width="15%"> <?php echo $f->username ?> </td>
                <td width="30%"> <?php echo $f->email ?> </td>
                <td width="15%"> <?php echo $f->livello ?> </td>
                <td width="10%"> <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>                   
                <td width="10%"><button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button> </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
</div>